name: PDF Converter Tests

on:
  push:
    branches:
      - '!master'
      - '!develop'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Build & Test PDF Converter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        if: always()
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Unit Tests
        shell: bash
        run: make unitTestCoverage
